Added Bandit stage

diff --git a/.github/workflows/devsecops.yml b/.github/workflows/devsecops.yml
--- a/.github/workflows/devsecops.yml
+++ b/.github/workflows/devsecops.yml
@@ -26,27 +26,27 @@ jobs:
         uses: actions/checkout@v4
 
       # Set a dynamic file name for the report
-      - name: Set JSON report file name
-        run: echo "REPORT_NAME=trivy-fs-report-$(date +'%Y-%m-%d_%H-%M').json" >> $GITHUB_ENV
+      - name: Set Trivy JSON report file name
+        run: echo "TRIVY_REPORT_NAME=trivy-fs-report-$(date +'%Y-%m-%d_%H-%M').json" >> $GITHUB_ENV
 
       # Run Trivy in fs mode, create a JSON report
       - name: Run Trivy in fs mode, generate JSON vulnerability report
         uses: aquasecurity/trivy-action@master  #trivy-action says 0.28.0
         with:
           scan-type: "fs"
-          output: '${{ env.REPORT_NAME }}'
+          output: '${{ env.TRIVY_REPORT_NAME }}'
           format: 'json'
           scan-ref: '.'
           exit-code: '0'
           # Enable next line for ad-hoc analysis
           #trivy-config: trivy.yaml  # I should create this file, in case
       
-      # Upload the JSON report
+      # Upload the Trivy JSON report
       - name: Upload vulnerability scan results (JSON)
         uses: actions/upload-artifact@v4
         with:
           name: trivy-fs_json-report
-          path: ${{ env.REPORT_NAME }}
+          path: ${{ env.TRIVY_REPORT_NAME }}
           retention-days: 30
 
       # Run Trivy in fs mode, create a SARIF report
@@ -84,6 +84,69 @@ jobs:
           exit-code: '1'
           skip-setup-trivy: true
 
+  # Bandit to do Static Application Security Test (SAST)
+  sast:
+    permissions:
+      contents: read            # for actions/checkout to fetch code
+      security-events: write    # for github/codeql-action/upload-sarif to upload SARIF results
+      actions: read             # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
+    name: SAST
+    runs-on: ubuntu-latest
+    steps:
+      # Checkout code
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      # Set up Python
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.x'
+
+      # Install Bandit, including support for SARIF and TOML files
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install bandit[sarif,toml]
+
+      # Set a dynamic file name for the JSON report
+      - name: Set Bandit JSON report file name
+        run: echo "BANDIT_REPORT_NAME=bandit-report-$(date +'%Y-%m-%d_%H-%M').json" >> $GITHUB_ENV
+
+      # Run Bandit to do SAST, generate JSON and SARIF reports
+      - name: Run Bandit, generate reports
+        run: | 
+          bandit -r . -f json -o "${{ env.BANDIT_REPORT_NAME }}" --severity-level high
+          bandit -r . -f sarif -o bandit-sarif-report.sarif
+
+      # Check the JSON report for high-severity vulnerabilities, exit if it's found
+      - name: Check for vulnerabilities (Bandit)
+        run: | 
+          cat "${{ env.BANDIT_REPORT_NAME }}"
+          if grep -q '"severity": "HIGH"' "${{ env.BANDIT_REPORT_NAME }}"; then
+            echo "High severity vulnerabilities found!"
+            exit 1
+          else
+            echo "No high severity vulnerabilities found."
+          fi
+
+      # Upload the Bandit JSON report
+      - name: Upload Bandit scan results (JSON)
+        uses: actions/upload-artifact@v4
+        with:
+          name: bandit-json-report
+          path: ${{ env.BANDIT_REPORT_NAME }}
+          retention-days: 30
+
+      # Upload Bandit SARIF results to GitHub Security tab
+      - name: Upload vulnerability scan results (sarif)
+        uses: github/codeql-action/upload-sarif@v3
+        # Upload SARIF results to GitHub Code scanning even upon a non zero exit code from Trivy Scan
+        if: always()
+        with:
+          sarif_file: 'bandit-sarif-report.sarif'
+
+
   # Trivy to do Infrastructure as Code (IaC) scanning
   iac-scan:
     permissions:
@@ -120,7 +183,7 @@ jobs:
           sarif_file: 'trivy-iac_sarif-report.sarif'
 
 
-  # Bandit to do Static Application Security Test (SAST)?
+
 
 
   # Trivy to do Container Scanning?
